"""from json import load

with open("boho_grammar.json") as f:
    grammar = load(f)
    print(grammar)"""

boho_grammar = [{'boho': {'1': {'': ['":"']},
                          '0': {'/': '49', '\\n': '47', '\\|': '48', '\\d': '46', '@': '45', '"': '35', "'": '36',
                                '[A-Z]': '30', '_': '31', '[a-z]': '26', '\\+': '24', '\\*': '23', '\\?': '22',
                                '\\)': '16', '\\(': '15', '-': '13', '%': '3', '#': '2', ':': '1'}, '2': {'': ['"#"']},
                          '3': {'i': '4'}, '4': {'g': '5'}, '5': {'n': '6'}, '6': {'o': '7'}, '7': {'r': '8'},
                          '8': {'e': '9'}, '9': {'': ['"%ignore"']}, '10': {'>': '11'}, '11': {'': ['"->"']},
                          '12': {'': ['"-"'], '>': '11'}, '13': {'-': '14', '': ['"-"'], '>': '11'},
                          '14': {'': ['"--"']}, '15': {'': ['"("']}, '16': {'': ['")"']}, '17': {'/': '18'},
                          '18': {'': ['///([^\\n]*[^/])?/'], '\\n': '19', '[\\v-.]': '18', '/': '20', '[^\\n-/]': '18'},
                          '19': {'': ['///([^\\n]*[^/])?/']},
                          '20': {'\\n': '19', '[\\v-.]': '18', '/': '20', '[^\\n-/]': '18'},
                          '21': {'': ['_NL'], '[\\t\\v\\f\\r ]': '21', '\\n': '21'}, '22': {'': ['Q']},
                          '23': {'': ['S']}, '24': {'': ['P']}, '25': {'[a-z]': '26'},
                          '26': {'': ['L_NAME'], '_': '26', '[a-z]': '26'}, '27': {'[A-Z]': '27', '_': '29'},
                          '28': {'[A-Z]': '27', '[a-z]': '26'}, '29': {'': ['F_NAME'], '[A-Z]': '27', '_': '29'},
                          '30': {'': ['U_NAME'], '[A-Z]': '30', '_': '32'},
                          '31': {'[A-Z]': '30', '_': '33', '[a-z]': '26'},
                          '32': {'[A-Z]': '30', '_': '32', '': ['F_NAME']}, '33': {'[A-Z]': '34', '_': '33'},
                          '34': {'': ['U_NAME'], '[A-Z]': '34', '_': '33'},
                          '35': {'[^\\n"]': '35', '\\\\': '37', '"': '38'},
                          '36': {"[^\\n']": '36', '\\\\': '39', "'": '38'}, '37': {'.': '35'}, '38': {'': ['STR']},
                          '39': {'.': '36'},
                          '40': {'[+-.]': '41', '[0-\\[]': '41', '\\\\': '42', '[^*-\\\\]': '41', '/': '18'},
                          '41': {'\\*': '41', '[+-.]': '41', '/': '43', '[0-\\[]': '41', '\\\\': '42',
                                 '[^*-\\\\]': '41'},
                          '42': {'\\*': '41', '[+-.]': '41', '/': '44', '[0-\\[]': '41', '\\\\': '42',
                                 '[^*-\\\\]': '41'}, '43': {'': ['REGEX']},
                          '44': {'': ['REGEX'], '\\*': '41', '[+-.]': '41', '/': '43', '[0-\\[]': '41', '\\\\': '42',
                                 '[^*-\\\\]': '41'}, '45': {'': ['AT'], '[A-Z_]': '45'}, '46': {'': ['N'], '\\d': '46'},
                          '47': {'[\\t\\v\\f\\r ]': '47', '\\n': '47', '\\|': '48', '': ['_NL']},
                          '48': {'': ['_OR'], '[\\t\\v\\f\\r ]': '48', '\\n': '48'},
                          '49': {'\\*': '50', '[+-.]|[0-\\[]|[^*-\\\\]': '41', '\\\\': '42', '/': '18'},
                          '50': {'': ['START', 'comment']}, '': [' ']}, 'comment': {'2': {'': ['START', 'comment']},
                                                                                    '0': {'\\*': '52', '[+-.]': '53',
                                                                                          '/': '1', '[^*-/]': '53'},
                                                                                    '1': {'': ['CONTENT'], '\\*': '2'},
                                                                                    '50': {'/': '51'},
                                                                                    '51': {'': ['STOP', 1]},
                                                                                    '52': {'': ['CONTENT'], '/': '51'},
                                                                                    '53': {'': ['CONTENT'],
                                                                                           '[+-.]': '53',
                                                                                           '[^*-/]': '53'}}}, {
                    '0': {'start': '1', '_statements': '2', '_statement': '3', '_NL': '4', 'terminal': '5',
                          'nonterminal': '6', 'mode': '7', 'ignore': '8', '_LONG_COMMENT_': '9', 'U_NAME': '10',
                          '_name': '11', '"#"': '12', '"%ignore"': '13', 'START': '14', 'L_NAME': '15', 'F_NAME': '16'},
                    '1': {'$': True},
                    '2': {'$': [1, 'start'], '_statement': '17', '_NL': '4', 'terminal': '5', 'nonterminal': '6',
                          'mode': '7', 'ignore': '8', '_LONG_COMMENT_': '9', 'U_NAME': '10', '_name': '11', '"#"': '12',
                          '"%ignore"': '13', 'START': '14', 'L_NAME': '15', 'F_NAME': '16'},
                    '3': {'$': [1, '_statements'], '"#"': [1, '_statements'], '"%ignore"': [1, '_statements'],
                          'F_NAME': [1, '_statements'], 'L_NAME': [1, '_statements'], 'START': [1, '_statements'],
                          'U_NAME': [1, '_statements'], '_NL': [1, '_statements']},
                    '4': {'$': [1, '_statement'], '"#"': [1, '_statement'], '"%ignore"': [1, '_statement'],
                          'F_NAME': [1, '_statement'], 'L_NAME': [1, '_statement'], 'START': [1, '_statement'],
                          'U_NAME': [1, '_statement'], '_NL': [1, '_statement']},
                    '5': {'$': [1, '_statement'], '"#"': [1, '_statement'], '"%ignore"': [1, '_statement'],
                          'F_NAME': [1, '_statement'], 'L_NAME': [1, '_statement'], 'START': [1, '_statement'],
                          'U_NAME': [1, '_statement'], '_NL': [1, '_statement']},
                    '6': {'$': [1, '_statement'], '"#"': [1, '_statement'], '"%ignore"': [1, '_statement'],
                          'F_NAME': [1, '_statement'], 'L_NAME': [1, '_statement'], 'START': [1, '_statement'],
                          'U_NAME': [1, '_statement'], '_NL': [1, '_statement']},
                    '7': {'$': [1, '_statement'], '"#"': [1, '_statement'], '"%ignore"': [1, '_statement'],
                          'F_NAME': [1, '_statement'], 'L_NAME': [1, '_statement'], 'START': [1, '_statement'],
                          'U_NAME': [1, '_statement'], '_NL': [1, '_statement']},
                    '8': {'$': [1, '_statement'], '"#"': [1, '_statement'], '"%ignore"': [1, '_statement'],
                          'F_NAME': [1, '_statement'], 'L_NAME': [1, '_statement'], 'START': [1, '_statement'],
                          'U_NAME': [1, '_statement'], '_NL': [1, '_statement']},
                    '9': {'$': [1, '_statement'], '"#"': [1, '_statement'], '"%ignore"': [1, '_statement'],
                          'F_NAME': [1, '_statement'], 'L_NAME': [1, '_statement'], 'START': [1, '_statement'],
                          'U_NAME': [1, '_statement'], '_NL': [1, '_statement']}, '10': {'":"': '18'},
                    '11': {'":"': '19'}, '12': {'L_NAME': '20'},
                    '13': {'description': '21', 'U_NAME': '22', 'STR': '23', 'REGEX': '24', 'AT': '25'},
                    '14': {'_content': '26', '_unit': '27', 'CONTENT': '28', '_LONG_COMMENT_': '29', 'START': '30'},
                    '15': {'":"': [1, '_name']}, '16': {'":"': [1, '_name']},
                    '17': {'$': [2, '_statements'], '"#"': [2, '_statements'], '"%ignore"': [2, '_statements'],
                           'F_NAME': [2, '_statements'], 'L_NAME': [2, '_statements'], 'START': [2, '_statements'],
                           'U_NAME': [2, '_statements'], '_NL': [2, '_statements']},
                    '18': {'description': '31', 'STR': '32', 'REGEX': '33', 'AT': '34'},
                    '19': {'options': '35', '_options': '36', 'option': '37', 'units': '38', '_more_units': '39',
                           'unit': '40', 'atom': '41', 'U_NAME': '42', '_name': '43', 'description': '44', '"("': '45',
                           'L_NAME': '46', 'F_NAME': '47', 'STR': '48', 'REGEX': '49', 'AT': '50'},
                    '20': {'$': [2, 'mode'], '"#"': [2, 'mode'], '"%ignore"': [2, 'mode'], 'F_NAME': [2, 'mode'],
                           'L_NAME': [2, 'mode'], 'START': [2, 'mode'], 'U_NAME': [2, 'mode'], '_NL': [2, 'mode']},
                    '21': {'$': [2, 'ignore'], '"#"': [2, 'ignore'], '"%ignore"': [2, 'ignore'],
                           'F_NAME': [2, 'ignore'], 'L_NAME': [2, 'ignore'], 'START': [2, 'ignore'],
                           'U_NAME': [2, 'ignore'], '_NL': [2, 'ignore']},
                    '22': {'$': [2, 'ignore'], '"#"': [2, 'ignore'], '"%ignore"': [2, 'ignore'],
                           'F_NAME': [2, 'ignore'], 'L_NAME': [2, 'ignore'], 'START': [2, 'ignore'],
                           'U_NAME': [2, 'ignore'], '_NL': [2, 'ignore']},
                    '23': {'$': [1, 'description'], '"#"': [1, 'description'], '"%ignore"': [1, 'description'],
                           'F_NAME': [1, 'description'], 'L_NAME': [1, 'description'], 'START': [1, 'description'],
                           'U_NAME': [1, 'description'], '_NL': [1, 'description']},
                    '24': {'$': [1, 'description'], '"#"': [1, 'description'], '"%ignore"': [1, 'description'],
                           'F_NAME': [1, 'description'], 'L_NAME': [1, 'description'], 'START': [1, 'description'],
                           'U_NAME': [1, 'description'], '_NL': [1, 'description']},
                    '25': {'$': [1, 'description'], '"#"': [1, 'description'], '"%ignore"': [1, 'description'],
                           'F_NAME': [1, 'description'], 'L_NAME': [1, 'description'], 'START': [1, 'description'],
                           'U_NAME': [1, 'description'], '_NL': [1, 'description']},
                    '26': {'STOP': '51', '_unit': '52', 'CONTENT': '28', '_LONG_COMMENT_': '29', 'START': '30'},
                    '27': {'STOP': [1, '_content'], 'CONTENT': [1, '_content'], 'START': [1, '_content']},
                    '28': {'STOP': [1, '_unit'], 'CONTENT': [1, '_unit'], 'START': [1, '_unit']},
                    '29': {'STOP': [1, '_unit'], 'CONTENT': [1, '_unit'], 'START': [1, '_unit']},
                    '30': {'_content': '53', '_unit': '27', 'CONTENT': '28', '_LONG_COMMENT_': '29', 'START': '30'},
                    '31': {'$': [3, 'terminal'], 'operations': '54', '"#"': [3, 'terminal'],
                           '"%ignore"': [3, 'terminal'], 'F_NAME': [3, 'terminal'], 'L_NAME': [3, 'terminal'],
                           'START': [3, 'terminal'], 'U_NAME': [3, 'terminal'], '_NL': [3, 'terminal'], '"->"': '55'},
                    '32': {'$': [1, 'description'], '"->"': [1, 'description'], '"#"': [1, 'description'],
                           '"%ignore"': [1, 'description'], 'F_NAME': [1, 'description'], 'L_NAME': [1, 'description'],
                           'START': [1, 'description'], 'U_NAME': [1, 'description'], '_NL': [1, 'description']},
                    '33': {'$': [1, 'description'], '"->"': [1, 'description'], '"#"': [1, 'description'],
                           '"%ignore"': [1, 'description'], 'F_NAME': [1, 'description'], 'L_NAME': [1, 'description'],
                           'START': [1, 'description'], 'U_NAME': [1, 'description'], '_NL': [1, 'description']},
                    '34': {'$': [1, 'description'], '"->"': [1, 'description'], '"#"': [1, 'description'],
                           '"%ignore"': [1, 'description'], 'F_NAME': [1, 'description'], 'L_NAME': [1, 'description'],
                           'START': [1, 'description'], 'U_NAME': [1, 'description'], '_NL': [1, 'description']},
                    '35': {'$': [3, 'nonterminal'], '"#"': [3, 'nonterminal'], '"%ignore"': [3, 'nonterminal'],
                           'F_NAME': [3, 'nonterminal'], 'L_NAME': [3, 'nonterminal'], 'START': [3, 'nonterminal'],
                           'U_NAME': [3, 'nonterminal'], '_NL': [3, 'nonterminal']},
                    '36': {'$': [1, 'options'], '"#"': [1, 'options'], '"%ignore"': [1, 'options'],
                           'F_NAME': [1, 'options'], 'L_NAME': [1, 'options'], 'START': [1, 'options'],
                           'U_NAME': [1, 'options'], '_NL': [1, 'options'], '_OR': '56'},
                    '37': {'$': [1, '_options'], '"#"': [1, '_options'], '"%ignore"': [1, '_options'],
                           'F_NAME': [1, '_options'], 'L_NAME': [1, '_options'], 'START': [1, '_options'],
                           'U_NAME': [1, '_options'], '_NL': [1, '_options'], '_OR': [1, '_options']},
                    '38': {'"->"': '57', '$': [1, 'option'], '"#"': [1, 'option'], '"%ignore"': [1, 'option'],
                           'F_NAME': [1, 'option'], 'L_NAME': [1, 'option'], 'START': [1, 'option'],
                           'U_NAME': [1, 'option'], '_NL': [1, 'option'], '_OR': [1, 'option']},
                    '39': {'"->"': [1, 'units'], '$': [1, 'units'], '"#"': [1, 'units'], '"%ignore"': [1, 'units'],
                           'F_NAME': '47', 'L_NAME': '46', 'START': [1, 'units'], 'U_NAME': '42', '_NL': [1, 'units'],
                           '_OR': [1, 'units'], 'unit': '58', 'atom': '41', '_name': '43', 'description': '44',
                           '"("': '45', 'STR': '48', 'REGEX': '49', 'AT': '50'},
                    '40': {'"->"': [1, '_more_units'], '$': [1, '_more_units'], '"#"': [1, '_more_units'],
                           '"%ignore"': [1, '_more_units'], 'F_NAME': [1, '_more_units'], 'L_NAME': [1, '_more_units'],
                           'START': [1, '_more_units'], 'U_NAME': [1, '_more_units'], '_NL': [1, '_more_units'],
                           '_OR': [1, '_more_units'], '"("': [1, '_more_units'], 'AT': [1, '_more_units'],
                           'REGEX': [1, '_more_units'], 'STR': [1, '_more_units']},
                    '41': {'quantifier': '59', '"->"': [1, 'unit'], '$': [1, 'unit'], '"#"': [1, 'unit'],
                           '"%ignore"': [1, 'unit'], 'F_NAME': [1, 'unit'], 'L_NAME': [1, 'unit'], 'START': [1, 'unit'],
                           'U_NAME': [1, 'unit'], '_NL': [1, 'unit'], '_OR': [1, 'unit'], '"("': [1, 'unit'],
                           'AT': [1, 'unit'], 'REGEX': [1, 'unit'], 'STR': [1, 'unit'], 'Q': '60', 'S': '61',
                           'P': '62'},
                    '42': {'P': [1, 'atom'], 'Q': [1, 'atom'], 'S': [1, 'atom'], '"->"': [1, 'atom'], '$': [1, 'atom'],
                           '"#"': [1, 'atom'], '"%ignore"': [1, 'atom'], 'F_NAME': [1, 'atom'], 'L_NAME': [1, 'atom'],
                           'START': [1, 'atom'], 'U_NAME': [1, 'atom'], '_NL': [1, 'atom'], '_OR': [1, 'atom'],
                           '"("': [1, 'atom'], 'AT': [1, 'atom'], 'REGEX': [1, 'atom'], 'STR': [1, 'atom']},
                    '43': {'P': [1, 'atom'], 'Q': [1, 'atom'], 'S': [1, 'atom'], '"->"': [1, 'atom'], '$': [1, 'atom'],
                           '"#"': [1, 'atom'], '"%ignore"': [1, 'atom'], 'F_NAME': [1, 'atom'], 'L_NAME': [1, 'atom'],
                           'START': [1, 'atom'], 'U_NAME': [1, 'atom'], '_NL': [1, 'atom'], '_OR': [1, 'atom'],
                           '"("': [1, 'atom'], 'AT': [1, 'atom'], 'REGEX': [1, 'atom'], 'STR': [1, 'atom']},
                    '44': {'P': [1, 'atom'], 'Q': [1, 'atom'], 'S': [1, 'atom'], '"->"': [1, 'atom'], '$': [1, 'atom'],
                           '"#"': [1, 'atom'], '"%ignore"': [1, 'atom'], 'F_NAME': [1, 'atom'], 'L_NAME': [1, 'atom'],
                           'START': [1, 'atom'], 'U_NAME': [1, 'atom'], '_NL': [1, 'atom'], '_OR': [1, 'atom'],
                           '"("': [1, 'atom'], 'AT': [1, 'atom'], 'REGEX': [1, 'atom'], 'STR': [1, 'atom']},
                    '45': {'options': '63', '_options': '64', 'option': '65', 'units': '66', '_more_units': '67',
                           'unit': '68', 'atom': '69', 'U_NAME': '70', '_name': '71', 'description': '72', '"("': '73',
                           'L_NAME': '74', 'F_NAME': '75', 'STR': '76', 'REGEX': '77', 'AT': '78'},
                    '46': {'P': [1, '_name'], 'Q': [1, '_name'], 'S': [1, '_name'], '"->"': [1, '_name'],
                           '$': [1, '_name'], '"#"': [1, '_name'], '"%ignore"': [1, '_name'], 'F_NAME': [1, '_name'],
                           'L_NAME': [1, '_name'], 'START': [1, '_name'], 'U_NAME': [1, '_name'], '_NL': [1, '_name'],
                           '_OR': [1, '_name'], '"("': [1, '_name'], 'AT': [1, '_name'], 'REGEX': [1, '_name'],
                           'STR': [1, '_name']},
                    '47': {'P': [1, '_name'], 'Q': [1, '_name'], 'S': [1, '_name'], '"->"': [1, '_name'],
                           '$': [1, '_name'], '"#"': [1, '_name'], '"%ignore"': [1, '_name'], 'F_NAME': [1, '_name'],
                           'L_NAME': [1, '_name'], 'START': [1, '_name'], 'U_NAME': [1, '_name'], '_NL': [1, '_name'],
                           '_OR': [1, '_name'], '"("': [1, '_name'], 'AT': [1, '_name'], 'REGEX': [1, '_name'],
                           'STR': [1, '_name']},
                    '48': {'P': [1, 'description'], 'Q': [1, 'description'], 'S': [1, 'description'],
                           '"->"': [1, 'description'], '$': [1, 'description'], '"#"': [1, 'description'],
                           '"%ignore"': [1, 'description'], 'F_NAME': [1, 'description'], 'L_NAME': [1, 'description'],
                           'START': [1, 'description'], 'U_NAME': [1, 'description'], '_NL': [1, 'description'],
                           '_OR': [1, 'description'], '"("': [1, 'description'], 'AT': [1, 'description'],
                           'REGEX': [1, 'description'], 'STR': [1, 'description']},
                    '49': {'P': [1, 'description'], 'Q': [1, 'description'], 'S': [1, 'description'],
                           '"->"': [1, 'description'], '$': [1, 'description'], '"#"': [1, 'description'],
                           '"%ignore"': [1, 'description'], 'F_NAME': [1, 'description'], 'L_NAME': [1, 'description'],
                           'START': [1, 'description'], 'U_NAME': [1, 'description'], '_NL': [1, 'description'],
                           '_OR': [1, 'description'], '"("': [1, 'description'], 'AT': [1, 'description'],
                           'REGEX': [1, 'description'], 'STR': [1, 'description']},
                    '50': {'P': [1, 'description'], 'Q': [1, 'description'], 'S': [1, 'description'],
                           '"->"': [1, 'description'], '$': [1, 'description'], '"#"': [1, 'description'],
                           '"%ignore"': [1, 'description'], 'F_NAME': [1, 'description'], 'L_NAME': [1, 'description'],
                           'START': [1, 'description'], 'U_NAME': [1, 'description'], '_NL': [1, 'description'],
                           '_OR': [1, 'description'], '"("': [1, 'description'], 'AT': [1, 'description'],
                           'REGEX': [1, 'description'], 'STR': [1, 'description']},
                    '51': {'$': [3, '_LONG_COMMENT_'], '"#"': [3, '_LONG_COMMENT_'], '"%ignore"': [3, '_LONG_COMMENT_'],
                           'F_NAME': [3, '_LONG_COMMENT_'], 'L_NAME': [3, '_LONG_COMMENT_'],
                           'START': [3, '_LONG_COMMENT_'], 'U_NAME': [3, '_LONG_COMMENT_'],
                           '_NL': [3, '_LONG_COMMENT_']},
                    '52': {'STOP': [2, '_content'], 'CONTENT': [2, '_content'], 'START': [2, '_content']},
                    '53': {'STOP': '79', '_unit': '52', 'CONTENT': '28', '_LONG_COMMENT_': '29', 'START': '30'},
                    '54': {'$': [4, 'terminal'], '"#"': [4, 'terminal'], '"%ignore"': [4, 'terminal'],
                           'F_NAME': [4, 'terminal'], 'L_NAME': [4, 'terminal'], 'START': [4, 'terminal'],
                           'U_NAME': [4, 'terminal'], '_NL': [4, 'terminal']},
                    '55': {'_operations': '80', '_operation': '81', 'push_mode': '82', 'pop_mode': '83',
                           'reset_mode': '84', 'change_mode': '85', 'P': '86', '"-"': '87', '"--"': '88',
                           'L_NAME': '89'},
                    '56': {'option': '90', 'units': '38', '_more_units': '39', 'unit': '40', 'atom': '41',
                           'U_NAME': '42', '_name': '43', 'description': '44', '"("': '45', 'L_NAME': '46',
                           'F_NAME': '47', 'STR': '48', 'REGEX': '49', 'AT': '50'},
                    '57': {'_name': '91', 'L_NAME': '92', 'F_NAME': '93'},
                    '58': {'"->"': [2, '_more_units'], '$': [2, '_more_units'], '"#"': [2, '_more_units'],
                           '"%ignore"': [2, '_more_units'], 'F_NAME': [2, '_more_units'], 'L_NAME': [2, '_more_units'],
                           'START': [2, '_more_units'], 'U_NAME': [2, '_more_units'], '_NL': [2, '_more_units'],
                           '_OR': [2, '_more_units'], '"("': [2, '_more_units'], 'AT': [2, '_more_units'],
                           'REGEX': [2, '_more_units'], 'STR': [2, '_more_units']},
                    '59': {'"->"': [2, 'unit'], '$': [2, 'unit'], '"#"': [2, 'unit'], '"%ignore"': [2, 'unit'],
                           'F_NAME': [2, 'unit'], 'L_NAME': [2, 'unit'], 'START': [2, 'unit'], 'U_NAME': [2, 'unit'],
                           '_NL': [2, 'unit'], '_OR': [2, 'unit'], '"("': [2, 'unit'], 'AT': [2, 'unit'],
                           'REGEX': [2, 'unit'], 'STR': [2, 'unit']},
                    '60': {'"->"': [1, 'quantifier'], '$': [1, 'quantifier'], '"#"': [1, 'quantifier'],
                           '"%ignore"': [1, 'quantifier'], 'F_NAME': [1, 'quantifier'], 'L_NAME': [1, 'quantifier'],
                           'START': [1, 'quantifier'], 'U_NAME': [1, 'quantifier'], '_NL': [1, 'quantifier'],
                           '_OR': [1, 'quantifier'], '"("': [1, 'quantifier'], 'AT': [1, 'quantifier'],
                           'REGEX': [1, 'quantifier'], 'STR': [1, 'quantifier']},
                    '61': {'"->"': [1, 'quantifier'], '$': [1, 'quantifier'], '"#"': [1, 'quantifier'],
                           '"%ignore"': [1, 'quantifier'], 'F_NAME': [1, 'quantifier'], 'L_NAME': [1, 'quantifier'],
                           'START': [1, 'quantifier'], 'U_NAME': [1, 'quantifier'], '_NL': [1, 'quantifier'],
                           '_OR': [1, 'quantifier'], '"("': [1, 'quantifier'], 'AT': [1, 'quantifier'],
                           'REGEX': [1, 'quantifier'], 'STR': [1, 'quantifier']},
                    '62': {'"->"': [1, 'quantifier'], '$': [1, 'quantifier'], '"#"': [1, 'quantifier'],
                           '"%ignore"': [1, 'quantifier'], 'F_NAME': [1, 'quantifier'], 'L_NAME': [1, 'quantifier'],
                           'START': [1, 'quantifier'], 'U_NAME': [1, 'quantifier'], '_NL': [1, 'quantifier'],
                           '_OR': [1, 'quantifier'], '"("': [1, 'quantifier'], 'AT': [1, 'quantifier'],
                           'REGEX': [1, 'quantifier'], 'STR': [1, 'quantifier']}, '63': {'")"': '94'},
                    '64': {'")"': [1, 'options'], '_OR': '95'}, '65': {'")"': [1, '_options'], '_OR': [1, '_options']},
                    '66': {'"->"': '96', '")"': [1, 'option'], '_OR': [1, 'option']},
                    '67': {'"->"': [1, 'units'], '")"': [1, 'units'], '_OR': [1, 'units'], 'unit': '97', 'atom': '69',
                           'U_NAME': '70', '_name': '71', 'description': '72', '"("': '73', 'L_NAME': '74',
                           'F_NAME': '75', 'STR': '76', 'REGEX': '77', 'AT': '78'},
                    '68': {'"->"': [1, '_more_units'], '")"': [1, '_more_units'], '_OR': [1, '_more_units'],
                           '"("': [1, '_more_units'], 'AT': [1, '_more_units'], 'F_NAME': [1, '_more_units'],
                           'L_NAME': [1, '_more_units'], 'REGEX': [1, '_more_units'], 'STR': [1, '_more_units'],
                           'U_NAME': [1, '_more_units']},
                    '69': {'quantifier': '98', '"->"': [1, 'unit'], '")"': [1, 'unit'], '_OR': [1, 'unit'],
                           '"("': [1, 'unit'], 'AT': [1, 'unit'], 'F_NAME': [1, 'unit'], 'L_NAME': [1, 'unit'],
                           'REGEX': [1, 'unit'], 'STR': [1, 'unit'], 'U_NAME': [1, 'unit'], 'Q': '99', 'S': '100',
                           'P': '101'},
                    '70': {'P': [1, 'atom'], 'Q': [1, 'atom'], 'S': [1, 'atom'], '"->"': [1, 'atom'],
                           '")"': [1, 'atom'], '_OR': [1, 'atom'], '"("': [1, 'atom'], 'AT': [1, 'atom'],
                           'F_NAME': [1, 'atom'], 'L_NAME': [1, 'atom'], 'REGEX': [1, 'atom'], 'STR': [1, 'atom'],
                           'U_NAME': [1, 'atom']},
                    '71': {'P': [1, 'atom'], 'Q': [1, 'atom'], 'S': [1, 'atom'], '"->"': [1, 'atom'],
                           '")"': [1, 'atom'], '_OR': [1, 'atom'], '"("': [1, 'atom'], 'AT': [1, 'atom'],
                           'F_NAME': [1, 'atom'], 'L_NAME': [1, 'atom'], 'REGEX': [1, 'atom'], 'STR': [1, 'atom'],
                           'U_NAME': [1, 'atom']},
                    '72': {'P': [1, 'atom'], 'Q': [1, 'atom'], 'S': [1, 'atom'], '"->"': [1, 'atom'],
                           '")"': [1, 'atom'], '_OR': [1, 'atom'], '"("': [1, 'atom'], 'AT': [1, 'atom'],
                           'F_NAME': [1, 'atom'], 'L_NAME': [1, 'atom'], 'REGEX': [1, 'atom'], 'STR': [1, 'atom'],
                           'U_NAME': [1, 'atom']},
                    '73': {'options': '102', '_options': '64', 'option': '65', 'units': '66', '_more_units': '67',
                           'unit': '68', 'atom': '69', 'U_NAME': '70', '_name': '71', 'description': '72', '"("': '73',
                           'L_NAME': '74', 'F_NAME': '75', 'STR': '76', 'REGEX': '77', 'AT': '78'},
                    '74': {'P': [1, '_name'], 'Q': [1, '_name'], 'S': [1, '_name'], '"->"': [1, '_name'],
                           '")"': [1, '_name'], '_OR': [1, '_name'], '"("': [1, '_name'], 'AT': [1, '_name'],
                           'F_NAME': [1, '_name'], 'L_NAME': [1, '_name'], 'REGEX': [1, '_name'], 'STR': [1, '_name'],
                           'U_NAME': [1, '_name']},
                    '75': {'P': [1, '_name'], 'Q': [1, '_name'], 'S': [1, '_name'], '"->"': [1, '_name'],
                           '")"': [1, '_name'], '_OR': [1, '_name'], '"("': [1, '_name'], 'AT': [1, '_name'],
                           'F_NAME': [1, '_name'], 'L_NAME': [1, '_name'], 'REGEX': [1, '_name'], 'STR': [1, '_name'],
                           'U_NAME': [1, '_name']},
                    '76': {'P': [1, 'description'], 'Q': [1, 'description'], 'S': [1, 'description'],
                           '"->"': [1, 'description'], '")"': [1, 'description'], '_OR': [1, 'description'],
                           '"("': [1, 'description'], 'AT': [1, 'description'], 'F_NAME': [1, 'description'],
                           'L_NAME': [1, 'description'], 'REGEX': [1, 'description'], 'STR': [1, 'description'],
                           'U_NAME': [1, 'description']},
                    '77': {'P': [1, 'description'], 'Q': [1, 'description'], 'S': [1, 'description'],
                           '"->"': [1, 'description'], '")"': [1, 'description'], '_OR': [1, 'description'],
                           '"("': [1, 'description'], 'AT': [1, 'description'], 'F_NAME': [1, 'description'],
                           'L_NAME': [1, 'description'], 'REGEX': [1, 'description'], 'STR': [1, 'description'],
                           'U_NAME': [1, 'description']},
                    '78': {'P': [1, 'description'], 'Q': [1, 'description'], 'S': [1, 'description'],
                           '"->"': [1, 'description'], '")"': [1, 'description'], '_OR': [1, 'description'],
                           '"("': [1, 'description'], 'AT': [1, 'description'], 'F_NAME': [1, 'description'],
                           'L_NAME': [1, 'description'], 'REGEX': [1, 'description'], 'STR': [1, 'description'],
                           'U_NAME': [1, 'description']},
                    '79': {'STOP': [3, '_LONG_COMMENT_'], 'CONTENT': [3, '_LONG_COMMENT_'],
                           'START': [3, '_LONG_COMMENT_']},
                    '80': {'$': [2, 'operations'], '"#"': [2, 'operations'], '"%ignore"': [2, 'operations'],
                           'F_NAME': [2, 'operations'], 'L_NAME': '89', 'START': [2, 'operations'],
                           'U_NAME': [2, 'operations'], '_NL': [2, 'operations'], '_operation': '103',
                           'push_mode': '82', 'pop_mode': '83', 'reset_mode': '84', 'change_mode': '85', 'P': '86',
                           '"-"': '87', '"--"': '88'},
                    '81': {'$': [1, '_operations'], '"#"': [1, '_operations'], '"%ignore"': [1, '_operations'],
                           'F_NAME': [1, '_operations'], 'L_NAME': [1, '_operations'], 'START': [1, '_operations'],
                           'U_NAME': [1, '_operations'], '_NL': [1, '_operations'], '"-"': [1, '_operations'],
                           '"--"': [1, '_operations'], 'P': [1, '_operations']},
                    '82': {'$': [1, '_operation'], '"#"': [1, '_operation'], '"%ignore"': [1, '_operation'],
                           'F_NAME': [1, '_operation'], 'L_NAME': [1, '_operation'], 'START': [1, '_operation'],
                           'U_NAME': [1, '_operation'], '_NL': [1, '_operation'], '"-"': [1, '_operation'],
                           '"--"': [1, '_operation'], 'P': [1, '_operation']},
                    '83': {'$': [1, '_operation'], '"#"': [1, '_operation'], '"%ignore"': [1, '_operation'],
                           'F_NAME': [1, '_operation'], 'L_NAME': [1, '_operation'], 'START': [1, '_operation'],
                           'U_NAME': [1, '_operation'], '_NL': [1, '_operation'], '"-"': [1, '_operation'],
                           '"--"': [1, '_operation'], 'P': [1, '_operation']},
                    '84': {'$': [1, '_operation'], '"#"': [1, '_operation'], '"%ignore"': [1, '_operation'],
                           'F_NAME': [1, '_operation'], 'L_NAME': [1, '_operation'], 'START': [1, '_operation'],
                           'U_NAME': [1, '_operation'], '_NL': [1, '_operation'], '"-"': [1, '_operation'],
                           '"--"': [1, '_operation'], 'P': [1, '_operation']},
                    '85': {'$': [1, '_operation'], '"#"': [1, '_operation'], '"%ignore"': [1, '_operation'],
                           'F_NAME': [1, '_operation'], 'L_NAME': [1, '_operation'], 'START': [1, '_operation'],
                           'U_NAME': [1, '_operation'], '_NL': [1, '_operation'], '"-"': [1, '_operation'],
                           '"--"': [1, '_operation'], 'P': [1, '_operation']}, '86': {'L_NAME': '104'},
                    '87': {'$': [1, 'pop_mode'], 'N': '105', '"#"': [1, 'pop_mode'], '"%ignore"': [1, 'pop_mode'],
                           'F_NAME': [1, 'pop_mode'], 'L_NAME': [1, 'pop_mode'], 'START': [1, 'pop_mode'],
                           'U_NAME': [1, 'pop_mode'], '_NL': [1, 'pop_mode'], '"-"': [1, 'pop_mode'],
                           '"--"': [1, 'pop_mode'], 'P': [1, 'pop_mode']},
                    '88': {'$': [1, 'reset_mode'], '"#"': [1, 'reset_mode'], '"%ignore"': [1, 'reset_mode'],
                           'F_NAME': [1, 'reset_mode'], 'L_NAME': [1, 'reset_mode'], 'START': [1, 'reset_mode'],
                           'U_NAME': [1, 'reset_mode'], '_NL': [1, 'reset_mode'], '"-"': [1, 'reset_mode'],
                           '"--"': [1, 'reset_mode'], 'P': [1, 'reset_mode']},
                    '89': {'$': [1, 'change_mode'], '"#"': [1, 'change_mode'], '"%ignore"': [1, 'change_mode'],
                           'F_NAME': [1, 'change_mode'], 'L_NAME': [1, 'change_mode'], 'START': [1, 'change_mode'],
                           'U_NAME': [1, 'change_mode'], '_NL': [1, 'change_mode'], '"-"': [1, 'change_mode'],
                           '"--"': [1, 'change_mode'], 'P': [1, 'change_mode']},
                    '90': {'$': [3, '_options'], '"#"': [3, '_options'], '"%ignore"': [3, '_options'],
                           'F_NAME': [3, '_options'], 'L_NAME': [3, '_options'], 'START': [3, '_options'],
                           'U_NAME': [3, '_options'], '_NL': [3, '_options'], '_OR': [3, '_options']},
                    '91': {'$': [3, 'option'], '"#"': [3, 'option'], '"%ignore"': [3, 'option'],
                           'F_NAME': [3, 'option'], 'L_NAME': [3, 'option'], 'START': [3, 'option'],
                           'U_NAME': [3, 'option'], '_NL': [3, 'option'], '_OR': [3, 'option']},
                    '92': {'$': [1, '_name'], '"#"': [1, '_name'], '"%ignore"': [1, '_name'], 'F_NAME': [1, '_name'],
                           'L_NAME': [1, '_name'], 'START': [1, '_name'], 'U_NAME': [1, '_name'], '_NL': [1, '_name'],
                           '_OR': [1, '_name']},
                    '93': {'$': [1, '_name'], '"#"': [1, '_name'], '"%ignore"': [1, '_name'], 'F_NAME': [1, '_name'],
                           'L_NAME': [1, '_name'], 'START': [1, '_name'], 'U_NAME': [1, '_name'], '_NL': [1, '_name'],
                           '_OR': [1, '_name']},
                    '94': {'P': [3, 'atom'], 'Q': [3, 'atom'], 'S': [3, 'atom'], '"->"': [3, 'atom'], '$': [3, 'atom'],
                           '"#"': [3, 'atom'], '"%ignore"': [3, 'atom'], 'F_NAME': [3, 'atom'], 'L_NAME': [3, 'atom'],
                           'START': [3, 'atom'], 'U_NAME': [3, 'atom'], '_NL': [3, 'atom'], '_OR': [3, 'atom'],
                           '"("': [3, 'atom'], 'AT': [3, 'atom'], 'REGEX': [3, 'atom'], 'STR': [3, 'atom']},
                    '95': {'option': '106', 'units': '66', '_more_units': '67', 'unit': '68', 'atom': '69',
                           'U_NAME': '70', '_name': '71', 'description': '72', '"("': '73', 'L_NAME': '74',
                           'F_NAME': '75', 'STR': '76', 'REGEX': '77', 'AT': '78'},
                    '96': {'_name': '107', 'L_NAME': '108', 'F_NAME': '109'},
                    '97': {'"->"': [2, '_more_units'], '")"': [2, '_more_units'], '_OR': [2, '_more_units'],
                           '"("': [2, '_more_units'], 'AT': [2, '_more_units'], 'F_NAME': [2, '_more_units'],
                           'L_NAME': [2, '_more_units'], 'REGEX': [2, '_more_units'], 'STR': [2, '_more_units'],
                           'U_NAME': [2, '_more_units']},
                    '98': {'"->"': [2, 'unit'], '")"': [2, 'unit'], '_OR': [2, 'unit'], '"("': [2, 'unit'],
                           'AT': [2, 'unit'], 'F_NAME': [2, 'unit'], 'L_NAME': [2, 'unit'], 'REGEX': [2, 'unit'],
                           'STR': [2, 'unit'], 'U_NAME': [2, 'unit']},
                    '99': {'"->"': [1, 'quantifier'], '")"': [1, 'quantifier'], '_OR': [1, 'quantifier'],
                           '"("': [1, 'quantifier'], 'AT': [1, 'quantifier'], 'F_NAME': [1, 'quantifier'],
                           'L_NAME': [1, 'quantifier'], 'REGEX': [1, 'quantifier'], 'STR': [1, 'quantifier'],
                           'U_NAME': [1, 'quantifier']},
                    '100': {'"->"': [1, 'quantifier'], '")"': [1, 'quantifier'], '_OR': [1, 'quantifier'],
                            '"("': [1, 'quantifier'], 'AT': [1, 'quantifier'], 'F_NAME': [1, 'quantifier'],
                            'L_NAME': [1, 'quantifier'], 'REGEX': [1, 'quantifier'], 'STR': [1, 'quantifier'],
                            'U_NAME': [1, 'quantifier']},
                    '101': {'"->"': [1, 'quantifier'], '")"': [1, 'quantifier'], '_OR': [1, 'quantifier'],
                            '"("': [1, 'quantifier'], 'AT': [1, 'quantifier'], 'F_NAME': [1, 'quantifier'],
                            'L_NAME': [1, 'quantifier'], 'REGEX': [1, 'quantifier'], 'STR': [1, 'quantifier'],
                            'U_NAME': [1, 'quantifier']}, '102': {'")"': '110'},
                    '103': {'$': [2, '_operations'], '"#"': [2, '_operations'], '"%ignore"': [2, '_operations'],
                            'F_NAME': [2, '_operations'], 'L_NAME': [2, '_operations'], 'START': [2, '_operations'],
                            'U_NAME': [2, '_operations'], '_NL': [2, '_operations'], '"-"': [2, '_operations'],
                            '"--"': [2, '_operations'], 'P': [2, '_operations']},
                    '104': {'$': [2, 'push_mode'], '"#"': [2, 'push_mode'], '"%ignore"': [2, 'push_mode'],
                            'F_NAME': [2, 'push_mode'], 'L_NAME': [2, 'push_mode'], 'START': [2, 'push_mode'],
                            'U_NAME': [2, 'push_mode'], '_NL': [2, 'push_mode'], '"-"': [2, 'push_mode'],
                            '"--"': [2, 'push_mode'], 'P': [2, 'push_mode']},
                    '105': {'$': [2, 'pop_mode'], '"#"': [2, 'pop_mode'], '"%ignore"': [2, 'pop_mode'],
                            'F_NAME': [2, 'pop_mode'], 'L_NAME': [2, 'pop_mode'], 'START': [2, 'pop_mode'],
                            'U_NAME': [2, 'pop_mode'], '_NL': [2, 'pop_mode'], '"-"': [2, 'pop_mode'],
                            '"--"': [2, 'pop_mode'], 'P': [2, 'pop_mode']},
                    '106': {'")"': [3, '_options'], '_OR': [3, '_options']},
                    '107': {'")"': [3, 'option'], '_OR': [3, 'option']},
                    '108': {'")"': [1, '_name'], '_OR': [1, '_name']},
                    '109': {'")"': [1, '_name'], '_OR': [1, '_name']},
                    '110': {'P': [3, 'atom'], 'Q': [3, 'atom'], 'S': [3, 'atom'], '"->"': [3, 'atom'],
                            '")"': [3, 'atom'], '_OR': [3, 'atom'], '"("': [3, 'atom'], 'AT': [3, 'atom'],
                            'F_NAME': [3, 'atom'], 'L_NAME': [3, 'atom'], 'REGEX': [3, 'atom'], 'STR': [3, 'atom'],
                            'U_NAME': [3, 'atom']}, '': ['///([^\\n]*[^/])?/']}]
